'    agent any' 
'    environment {' 
'        DOCKER_IMAGE = "my-dl-project"' 
'    }' 
'    stages {' 
'        stage("Checkout") {' 
'            steps {' 
'                git branch: "master", url: "https://github.com/yourusername/yourrepository.git"' 
'            }' 
'        }' 
'        stage("Build Docker Image") {' 
'            steps {' 
'                script {' 
'                    sh "docker build -t $DOCKER_IMAGE ."' 
'                }' 
'            }' 
'        }' 
'        stage("Test Docker Image") {' 
'            steps {' 
'                script {' 
'                    sh "docker run --rm $DOCKER_IMAGE bash -c \"python -m unittest discover tests/\""' 
'                }' 
'            }' 
'        }' 
'        stage("Push Docker Image") {' 
'            steps {' 
'                script {' 
'                    sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"' 
'                    sh "docker tag $DOCKER_IMAGE $DOCKER_REGISTRY/$DOCKER_IMAGE"' 
'                    sh "docker push $DOCKER_REGISTRY/$DOCKER_IMAGE"' 
'                }' 
'            }' 
'        }' 
'    }' 
'    post {' 
'        success {' 
'            echo "Build and Deployment successful!"' 
'        }' 
'        failure {' 
'            echo "Build or Deployment failed."' 
'        }' 
'    }' 
'}' 
